/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmpleadosProductosVentas;

import java.util.ArrayList;

/**
 *
 * @author ilichh1
 */
public class Menu extends javax.swing.JFrame {
    private ArrayList<Vendedor> vendedores = null;
    private ArrayList<Producto> productos = null;
    private ListaVentas ventas = null;
    
    /**
     * Creates new form Menu
     * @param v Array list de Vendedor
     * @param p Array list de Producto
     * @param lv Lista ligada doble de ventas
     */
    public Menu(
            ArrayList<Vendedor> v,
            ArrayList<Producto> p,
            ListaVentas lv
    ) {
        vendedores = v;
        productos = p;
        ventas = lv;
        setResizable(false);
        setLocationRelativeTo(null);
        initComponents();
        customInit();
    }
    
    private void customInit() {
        vendedorForm.setVendedores(vendedores);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabNames = new javax.swing.JTabbedPane();
        vendedorForm = new EmpleadosProductosVentas.VendedorForm();
        productosForm1 = new EmpleadosProductosVentas.ProductosForm(productos);
        ventasForm = new EmpleadosProductosVentas.VentasForm(vendedores,productos,ventas);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        tabNames.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabNamesStateChanged(evt);
            }
        });
        tabNames.addTab("Vendedores", vendedorForm);
        tabNames.addTab("Productos", productosForm1);
        tabNames.addTab("Ventas", ventasForm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabNames, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabNames, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabNamesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabNamesStateChanged
        String ventasName = VentasForm.class.getName();
        String selectedName = tabNames.getSelectedComponent().getClass().getName();
        // Si el nombre del componente seleccionado es el de formulario de ventas
        if (ventasName.equals(selectedName)) {
            System.out.println("ACUTALIZAR VENDEDORES Y PRODUCTOS");
            ventasForm.initCombos();
        }
    }//GEN-LAST:event_tabNamesStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private EmpleadosProductosVentas.ProductosForm productosForm1;
    private javax.swing.JTabbedPane tabNames;
    private EmpleadosProductosVentas.VendedorForm vendedorForm;
    private EmpleadosProductosVentas.VentasForm ventasForm;
    // End of variables declaration//GEN-END:variables
}
