/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmpleadosProductosVentas;

import java.util.ArrayList;

/**
 *
 * @author ilichh1
 */
public class VentasForm extends javax.swing.JPanel {
    private final ArrayList<Vendedor> vendedores;
    private final ArrayList<Producto> productos;
    private final ListaVentas ventas;

    /**
     * Creates new form VentasForm
     */
    public VentasForm() {
        vendedores = new ArrayList<>();
        productos = new ArrayList<>();
        ventas = new ListaVentas();
        initComponents();
        initCombos();
    }
    
    public VentasForm(
            ArrayList<Vendedor> v,
            ArrayList<Producto> p,
            ListaVentas ven
    ) {
        vendedores = v;
        productos = p;
        ventas = ven;
        initComponents();
        initCombos();
    }
    
    public void initCombos() {
        // El "ID" inicial
        codigoTxt.setText(getId()+"");
        // Vendedores comboBox
        Vendedor[] vendedoresArr = vendedores.toArray(new Vendedor[vendedores.size()]);
        vendedoresCombo.setModel(new javax.swing.DefaultComboBoxModel<>(vendedoresArr));
        // Productos comboBox
        Producto[] productosArr = productos.toArray(new Producto[productos.size()]);
        productosCombo.setModel(new javax.swing.DefaultComboBoxModel<>(productosArr));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        productosCombo = new javax.swing.JComboBox<>();
        codigoTxt = new javax.swing.JTextField();
        vendedoresCombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        codigoLabel = new javax.swing.JLabel();
        productoLabel = new javax.swing.JLabel();
        vendedorLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Registro de ventas");

        jLabel2.setText("Codigo");

        jLabel3.setText("Vendedor");

        jLabel4.setText("Producto");

        productosCombo.setModel(new javax.swing.DefaultComboBoxModel<>());

        codigoTxt.setEditable(false);
        codigoTxt.setText("0");
        codigoTxt.setEnabled(false);

        vendedoresCombo.setModel(new javax.swing.DefaultComboBoxModel<>());

        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        anterior.setText("<");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });

        siguiente.setText(">");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        codigoLabel.setText("Código:");

        productoLabel.setText("Producto:");

        vendedorLabel.setText("Vendedor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codigoTxt)
                                    .addComponent(productosCombo, 0, 305, Short.MAX_VALUE)
                                    .addComponent(vendedoresCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(productoLabel)
                                .addGap(3, 3, 3))
                            .addComponent(vendedorLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(codigoLabel)
                                .addGap(14, 14, 14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addComponent(jSeparator2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(vendedoresCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(productosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(codigoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anterior)
                    .addComponent(siguiente)
                    .addComponent(productoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vendedorLabel)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        guardar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        anterior();
    }//GEN-LAST:event_anteriorActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        siguiente();
    }//GEN-LAST:event_siguienteActionPerformed

    private void guardar() {
        int id = getId();
        Producto pr = (Producto)productosCombo.getSelectedItem();
        Vendedor ve = (Vendedor)vendedoresCombo.getSelectedItem();
        ventas.insertarAlFinal(new Venta(id, pr, ve));
        limpiarInputs();
    }
    
    private void siguiente() {
        imprimirLabels(ventas.getSiguiente());
    }
    
    private void anterior() {
        imprimirLabels(ventas.getAnterior());
    }
    
    private void imprimirLabels(Venta venta) {
        int c = venta.getId();
        String v = venta.getVendedor().toString();
        String p = venta.getProducto().toString();
        codigoLabel.setText(c+"");
        productoLabel.setText(p);
        vendedorLabel.setText(v);
    }
    
    private void limpiarInputs() {
        codigoTxt.setText(getId()+"");
        vendedoresCombo.setSelectedItem(null);
        productosCombo.setSelectedItem(null);
    }
    
    private int getId() {
        return ventas.getLargo() + 1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel productoLabel;
    private javax.swing.JComboBox<Producto> productosCombo;
    private javax.swing.JButton siguiente;
    private javax.swing.JLabel vendedorLabel;
    private javax.swing.JComboBox<Vendedor> vendedoresCombo;
    // End of variables declaration//GEN-END:variables
}
